---
# FR: J'enregistre pluslieurs de mes données dans InfluxDB qui me permet
#     d'accéder à un historique plus ancien. J'utilise l'addon pour cela.
# EN: I store a lot of sensor data into InfluxDB, which allows me to query
#     a longer history with ease. I use the Community Hass.io add-on for this.
#
# https://github.com/hassio-addons/addon-influxdb
# https://www.home-assistant.io/components/influxdb/
#
influxdb:
  host: !secret local_ip_influxdb
  port: !secret port_influxdb
  database: homeassistant
  username: !secret influxdb_user_name
  password: !secret influxdb_user_password
  max_retries: 3
  default_measurement: state
  include:
    entities:
      # System monitoring
      - sensor.disk_use_percent
      - sensor.memory_use_percent
      - sensor.processor_use

      # Internet cnx monitoring
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload

      # UPC monitor
      - sensor.upc_back_ups_status

      # Outdoor weather monitoring
      - sensor.exterieur_humidity
      - sensor.exterieur_temperature
      - sensor.home_wind_speed
      - sensor.home_next_rain
      - sensor.home_temperature
      - sensor.home_weather_alert
      - sensor.home_uv
      - sensor.home_cloud_cover
      - sensor.home_daily_precipitation

      # Renault Zoe monitoring
      - binary_sensor.zoe_charging
      - binary_sensor.zoe_plugged_in
      - sensor.zoe_battery_level
      - sensor.zoe_curent_week_mileage
      - sensor.zoe_battery_autonomy
      - sensor.zoe_mileage
      - sensor.zoe_range
      - sensor.zoe_mileage_diff
      - variable.zoe_weekly_mileage

      # Electrical consumtion monitoring
      - sensor.prise_pc_power
      - sensor.prise_tv_power

      # Commute monitoring
      - sensor.trajet_maison_travail_alex
      - sensor.trajet_maison_travail_benoit

      # Security sensors monitoring
      - sensor.detecteur_de_fumee_temperature
      - binary_sensor.garage_door
      - binary_sensor.main_door
      - binary_sensor.water_leak_sensor_buanderie

      # rooms conditons
      - sensor.temperature_athenais
      - sensor.temperature_noah
      - sensor.temperature_parents
      - sensor.temperature_salon
      - sensor.temperature_soren
      - sensor.temperature_sous_sol
      - sensor.temperature_bureau
      - sensor.humidity_parents
      - sensor.humidity_sous_sol
      - sensor.humidity_salon

      # scripts
      - script.vacuum_workday_sequence
      - script.launch_daily_vacuum_in_room

      # Others
      - binary_sensor.workday_sensor
      - vacuum.rocky

      # Pool Filtering Pump
      - switch.esphome_pompe_piscine_switch
