---
# FR: Vérifie si la porte du sous-sol est toujours ouverte à la tombée de la nuit
# EN: Check if cellar door is close at night
#
# FR: Si la porte est toujours ouverte, envoie une notification sur Telegram
# EN: If door is open, send a notification on telegram
#
# https://www.home-assistant.io/components/sun/
#
- alias: "Vérfie fermeture de la porte du sous-sol"
  description: Vérifie si la porte du sous-sol est toujours ouverte à la tombée de la nuit
  id: 0af06320-3082-11eb-8655-7fbd7c468bda
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.porte_sous_sol
      state: "on"
  action:
    - service: script.notification_engine
      data:
        who: Telegram Famille
        message: "La porte du sous-sol est toujours ouverte ! Un volontaire pour aller la fermer ?"
        add_audio: true
        audio_message: "Chers résidents, la porte du garage est ouverte. L'un d'entre vous doit aller la fermer."
