---
# FR: Intialiser tous les booleens utilisés par la routine de nettoyage avec le robot aspirateur à 5h00
# EN: Set all input_boolean entities used fot vacuum daily routine at 05:00 AM
#
- alias: "Initialisation de la routine de Rocky"
  description: Intialiser tous les booleens utilisés par la routine de nettoyage avec le robot aspirateur à 5h00
  id: e9d01ae0-3087-11eb-8655-7fbd7c468bda
  trigger:
    platform: time
    at: "05:00:00"
  action:
    # First stop the previous cleaning if started and send Vacuum to docking station.
    # Sometimes family stop the vacuum and it stays idle in the midlle of the house.
    - service: script.turn_on
      entity_id: script.stop_vacuum_workday_sequence

    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.vacuum_can_clean_athenais_bedroom
        - input_boolean.vacuum_can_clean_noah_bedroom
        - input_boolean.vacuum_can_clean_soren_bedroom
        - input_boolean.vacuum_can_clean_the_living_room
        - input_boolean.vacuum_can_clean_the_carpet
        - input_boolean.vacuum_can_clean_the_office
        - input_boolean.vacuum_can_clean_parental_suite
        - input_boolean.vacuum_can_clean_kids_bathroom

    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.vacuum_can_clean_the_entrance
        - input_boolean.vacuum_can_clean_the_kitchen
        - input_boolean.vacuum_can_clean_the_living_room_safe
        - input_boolean.vacuum_can_clean_the_coridor
