---
# FR: Mise à jour du kilmoétrage hebdomadaire de la semaine precedente. Variable 'zoe_weekly_mileage'
# EN: Update the previous week weekly mileage 'zoe_weekly_mileage' variable
#
# FR: Calcul le kilométrage hebdomadaire et le compare à la cible prévue. Envoie une notification tous les dimanches
#    avec l'ecart entre le réalisé et la cible.
# EN: Compute the weekly mileage and compare it to the weekly target. Send a notification every Saturday with the gap
#    between achieved and target.
#
# https://github.com/rogro82/hass-variables/
#
- alias: "Mise à jour du kilométrage hebdomadaire de la Zoé"
  description: "Mise à jour du kilmoétrage hebdomadaire de la Zoé pour la dernière semaine complète écoulée"
  id: 38a55c3c-042f-11eb-adc1-0242ac120002
  # update every monday at 00h00
  trigger:
    - platform: time
      at: "00:00:00"
  condition: "{{ now().isoweekday() == 1 }}"
  action:
    - service: variable.set_variable
      data:
        variable: zoe_weekly_mileage
        attributes:
          last_mileage: "{{ states('sensor.zoe_mileage') }}"
        value: >
          {{ states('sensor.zoe_mileage') | int
          - state_attr('variable.zoe_weekly_mileage', 'last_mileage') | int }}
    - service: script.notification_engine
      data:
        who: Moi
        message: >
          La Zoé a parcouru {{ states.variable.zoe_weekly_mileage.state_with_unit }} cette semaine.
          {% if states('variable.zoe_weekly_mileage') | int > 317 -%}
          C'est {{ states('variable.zoe_weekly_mileage') | int - 317 }} km de plus que prévu.
          {%- else -%}
          C'est {{ 317 - states('variable.zoe_weekly_mileage') | int  }} km de moins que prévu.
          {%- endif %}
