---
# FR: Alerte au redemarrage de HA core
# EN: Notification on HA core reboot
#
- alias: "Alerte au redemarrage de Home Assistant"
  description: Envoie une notification sur Telegram à chaque redemarrage de HA core
  id: 75093260-3086-11eb-8655-7fbd7c468bda
  condition: []
  trigger:
    - event: start
      platform: homeassistant
  action:
    - service: script.notification_engine
      data:
        who: Moi
        message: "Home Assitant a redémarré !"
