---
# FR: Lance une mesure Speedtest quatre fois par jour is le PC et la TV sont éteints
# EN: Launch Speedtest measures four times a day if PC and TV are off
#
- alias: "Lance Speedtest"
  description: Lance une mesure Speedtest deux fois par jour is le PC et la TV sont éteints
  id: d78a70d0-3085-11eb-8655-7fbd7c468bda
  trigger:
    platform: time_pattern
    hours: '/6'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: 'sensor.prise_pc_power'
        below: 25
      - condition: numeric_state
        entity_id: 'sensor.prise_tv_power'
        below: 5
  action:
    service: speedtestdotnet.speedtest
