---
# FR: Envoie une notificatin quand la pluie est attendue dans la prochaine heure
# EN: Sent a notification if rain is expected in the hour
#
# FR: - Envoie une notification texte la première fois que la pluie est attendue dans la prochaine heure.
#     - Envoie une notification texte et audio si la pluie est attendue dans moins de 5 minutes.
#     - Une fois qu'il pleue, évite de répéter les notifications jusqu'à plus de pluie attendue
#       dans la prochaine heure.
#
# EN: - Send a textual notification the first time the rain is expected in the hour.
#     - Send a textual and audio notification if rain is expected in less than 5 minutes.
#     - When it's raining, avoid to send notification until no more rain is expected in the
#       following hour.
#
# https://www.home-assistant.io/docs/automation/trigger/#template-trigger
# https://www.home-assistant.io/docs/scripts/conditions/#template-condition
#
- alias: Alerte quand pluie attendue
  description: Envoie des notifications quand la pluie est attendue dans l'heure
  id: 30f4e5a8-df44-11ea-87d0-0242ac130003
  trigger:
    platform: state
    entity_id: sensor.home_next_rain
  action:
    - choose:
        - conditions:
            # If rain is expected and notification are not stop by the input_boolean...
            - "{{ trigger.to_state.state != 'unknown' }}"
            - condition: state
              entity_id: input_boolean.stop_rain_notification
              state: 'off'
          sequence:
            - choose:
                - conditions:
                    # If first time rain is expected in less than one hour...
                    # ... Send a notification on Telegram
                    - "{{ trigger.from_state.state ==  'unknown'  }}"
                  sequence:
                    - service: script.notification_engine
                      data:
                        who: Moi
                        message: >
                          La pluie est attendue vers {{ as_timestamp(states('sensor.home_next_rain'))
                          | timestamp_custom('%H:%M', True) }}.
            - choose:
                - conditions:
                    # If rain is expected in less than 5 mintues...
                    # ... Stop future notification and send a notification audio and text
                    - "{{ state_attr('sensor.home_next_rain', '1_hour_forecast')['0 min'] != 'Temps sec' }}"
                  sequence:
                    - service: input_boolean.turn_on
                      data:
                        entity_id: input_boolean.stop_rain_notification
                    # Send a textual and an audio message (if not in daily quiet hours)
                    - service: script.notification_engine
                      data:
                        who: Moi
                        message: "La pluie est attendue dans quelques minutes."
                        add_audio: true
                        audio_message: "Chers résidents, la pluie est attendue dans quelques minutes."
                        do_not_disturb: true
        - conditions:
            # If rain is no more expected...
            # ... Send a notification on Telegram and allow future notifications
            - "{{ trigger.to_state.state == 'unknown' }}"
            - "{{ trigger.from_state.state != 'unknown' }}"
          sequence:
            - service: script.notification_engine
              data:
                who: Moi
                message: "Plus de pluie attendue dans la prochaine heure."
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.stop_rain_notification
