---
# FR: Vérifie si mon fils est au club de taekwondo et si c'est l'heure de partir la chercher.
# EN: Check if my son is in taekwondo club and if it's time to leave to get him.
#
# https://www.home-assistant.io/docs/automation/trigger/#time-trigger
# https://www.home-assistant.io/docs/scripts/conditions/#time-condition
#
- alias: "Vérfie s'il faut aller chercher Noah au club"
  description: Vérifie si c'est l'heure d'aller chercher Noah au club de taekwondo
  id: 592d4daf-3118-472b-8045-fb804c916adb
  # Time of notification change deppending of the training day
  trigger:
    - platform: time
      at: 
        - '20:20:00'
      id: "friday_time"
    - platform: time
      at: 
        - '20:05:00'
      id: "monday_time"
  # Notification if time and day match AND kid located in taekwondo club
  condition:
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: time
            weekday:
              - mon
          - condition: trigger
            id: monday_time
      - condition: and
        conditions:
          - condition: time
            weekday:
              - fri
          - condition: trigger
            id: friday_time
    - condition: zone
      entity_id: person.noah
      zone: zone.club_taekwondo
  action:
    - service: script.notification_engine
      data:
        who: Telegram Famille
        message: "C'est l'heure d'aller chercher Noah au club."
        add_audio: true
        audio_message: "Chers résidents, c'est l'heure d'aller chercher Noah au club."

