---
# E: Sensor to estimate evolution of maximum range of Renault Zoé
# when at 100%.
# F: Snesor pour estimer l'évolution de l'autonomie maximum quand
# la Zoé est à 100%
#
# https://github.com/epenet/hassRenaultZE
#
platform: template
sensors:
  zoe_max_range:
    value_template: >
      {% if (states('sensor.zoe_battery_level') | float != 0.0)
        and (states('sensor.zoe_battery_autonomy') is not none) %}
        {{ (states('sensor.zoe_battery_autonomy') | float
        / states('sensor.zoe_battery_level') | float * 100)
       | round(0) }}
      {% endif %}
    friendly_name: "Autonomie maximum à 100%"
    unit_of_measurement: "km"
